[supervisord]
nodaemon=true
user=root
minfds=10000
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/php-fpm.log

[program:queue-database]
command=php /var/www/html/artisan queue:work --queue=database --sleep=3 --tries=3
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-database.log

[program:queue-redis]
command=php /var/www/html/artisan queue:work redis --queue=chat --sleep=3 --tries=3
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-redis.log

[program:laravel-reverb]
command=php /var/www/html/artisan reverb:start
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/laravel-reverb.log

