name: linkedmeet

services:
    app:
        container_name: "app"
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        image: linkedmeet-app:latest
        ports:
            - "9000:9000"
            - "8080:8080"
        volumes:
            - app_data:/var/www/html
        depends_on:
            - mysql
            - redis
        mem_limit: 1g
        cpus: "0.5"
        networks:
            - linkedmeet
    frontend:
        container_name: "frontend"
        image: linkedmeet-frontend:latest
        ports:
            - "3000:3000"
        volumes:
            - frontend_data:/app
        depends_on:
            - app
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet
    mysql:
        container_name: "mysql"
        image: mysql:lts
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_INITDB_SKIP_TZINFO: 1
            MYSQL_MAX_CONNECTIONS: 100
            MYSQL_QUERY_CACHE_SIZE: 64M
        ports:
            - "3306:3306"
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        depends_on:
            - redis
        mem_limit: 1g
        cpus: "0.5"
        networks:
            - linkedmeet
    redis:
        container_name: "redis"
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet
    nginx:
        container_name: "nginx"
        image: nginx:latest
        volumes:
            - app_data:/var/www/html
            - frontend_data:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/certbot/www:/var/www/certbot/:ro
            - ./docker/nginx/certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - "80:80"
            - "443:443"
            - "3001:3001"
        restart: always
        depends_on:
            - app
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet
    certbot:
        container_name: "certbot"
        image: certbot/certbot:latest
        volumes:
            - ./docker/nginx/certbot/www:/var/www/certbot/:rw
            - ./docker/nginx/certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - linkedmeet

volumes:
    app_data:
    frontend_data:
    mysql_data:
    redis_data:

networks:
    linkedmeet:
        driver: bridge
