name: linkedmeet

services:
    app:
        container_name: "app"
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        image: linkedmeet-app
        ports:
            - "9000:9000"
            - "8080:8080"
        volumes:
            - app-data:/var/www/html
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started
        mem_limit: 1g
        cpus: "0.5"
        networks:
            - linkedmeet
    frontend:
        container_name: "frontend"
        image: linkedmeet-frontend:latest
        ports:
            - "3000:3000"
        volumes:
            - frontend-data:/app
        depends_on:
            - app
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet
    mysql:
        container_name: "mysql"
        image: mysql:lts
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_INITDB_SKIP_TZINFO: 1
            MYSQL_MAX_CONNECTIONS: 100
            MYSQL_QUERY_CACHE_SIZE: 64M
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        depends_on:
            - redis
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 30s
        mem_limit: 1g
        cpus: "0.5"
        networks:
            - linkedmeet

    redis:
        container_name: "redis"
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet

    nginx:
        container_name: "nginx"
        image: nginx:latest
        volumes:
            - app-data:/var/www/html
            - frontend-data:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "3001:3001"
        depends_on:
            - app
        mem_limit: 512m
        cpus: "0.25"
        networks:
            - linkedmeet

volumes:
    app-data:
        driver: local
    frontend-data:
        driver: local
    mysql-data:
        driver: local
    redis-data:
        driver: local

networks:
    linkedmeet:
        driver: bridge
