[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:migrate]
command=%(ENV_SUPERVISOR_MIGRATE_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-database]
process_name=%(program_name)s_%(process_num)02d
command=%(ENV_SUPERVISOR_QUEUE_DATABASE_COMMAND)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=%(ENV_SUPERVISOR_PHP_USER)s
numprocs=8
stopwaitsecs=3600
stdout_logfile=/var/log/queue-database.log
stderr_logfile=/var/log/queue-database-error.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

[program:queue-redis]
process_name=%(program_name)s_%(process_num)02d
command=%(ENV_SUPERVISOR_QUEUE_REDIS_COMMAND)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=%(ENV_SUPERVISOR_PHP_USER)s
numprocs=8
stopwaitsecs=3600
stdout_logfile=/var/log/queue-redis.log
stderr_logfile=/var/log/queue-redis-error.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

[program:reverb]
command=%(ENV_SUPERVISOR_REVERB_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
